name: learn-github-actions

on:
  workflow_call:
    inputs:
      thing:
        required: true
        type: string
      alert:
        required: true
        type: string
  workflow_dispatch:

jobs:
  display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs
        run: echo "thing = \"${{ inputs.thing }}\"" && echo "alert = \"${{ inputs.alert }}\""

  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v
